function rows = buildOutputTableRowsFromLog(trajectoryLog)
% buildOutputTableRowsFromLog - Build CSV rows directly from TrajectoryLog frames.
arguments
    trajectoryLog (1, 1) struct
end

rows = struct( ...
    'Time', {}, 'RandomMode', {}, 'ScenarioSeed', {}, ...
    'ID', {}, 'Class', {}, 'Subtype', {}, 'TargetSeed', {}, ...
    'X', {}, 'Y', {}, 'Z', {}, ...
    'Vx', {}, 'Vy', {}, 'Vz', {}, ...
    'RCS', {}, 'Visible', {}, 'State', {}, 'Mission', {}, ...
    'CurrentTreeID', {}, 'TargetTreeID', {}, ...
    'TransitionCount', {}, 'TransitionReason', {}, ...
    'WaypointIndex', {}, 'DistanceToWaypoint', {}, 'MissionComplete', {}, ...
    'NoProgressTime', {}, 'ForceDirectToWaypoint', {}, ...
    'TotalXYExcursion', {}, 'MaxAltitudeReached', {}, 'MinAltitudeReached', {}, ...
    'LastNavigationEvent', {}, ...
    'RoadID', {}, 'CurrentEdgeID', {}, 'Waypoint', {}, 'SpeedLimit', {}, 'RoadDeviation', {}, ...
    'RouteProgress', {}, 'OnRoad', {}, 'IsOffRoad', {}, 'DriverProfile', {}, 'GroundAction', {}, ...
    'DesiredSpeed', {}, 'DesiredAltitude', {}, 'CurrentHeading', {}, ...
    'TargetHeading', {}, 'LoiterRadius', {}, 'DiveTargetAltitude', {}, ...
    'FlightLevel', {}, 'TargetFlightLevel', {}, 'AltitudeError', {}, ...
    'DesiredClimbRate', {}, 'ClimbAngleDeg', {}, 'TurnSeverity', {}, ...
    'CornerCuttingActive', {}, ...
    'FinalPhase', {}, 'FinalStrategy', {}, 'FinalPhaseStarted', {}, ...
    'FinalMissionCompleted', {}, 'TimeInFinalPhase', {}, ...
    'DistanceToBoundary', {}, 'NearBoundary', {}, 'OutsideBoundary', {}, ...
    'BoundaryRecoveryActive', {}, 'LastBoundaryEvent', {}, ...
    'HeadingJumpDeg', {}, 'TargetPointJump', {}, 'AntiBounceActive', {}, ...
    'LastAntiBounceEvent', {}, 'TimeOnCurrentLeg', {}, ...
    'Decision', {}, ...
    'BehaviorAction', {}, 'BehaviorReason', {}, 'BehaviorGoal', {}, ...
    'BehaviorProfile', {}, ...
    'RouteIndex', {}, 'CurrentLegProgress', {}, 'BaseCruiseSpeed', {}, ...
    'CurrentSpeed', {}, 'TargetSpeed', {}, 'SpeedProfileEvent', {}, ...
    'CurrentFlightLevel', {}, 'HeadingErrorDeg', {}, 'TurnRateCommandDeg', {}, ...
    'AltitudeProfileEvent', {}, ...
    'InWarningZone', {}, 'InCriticalZone', {}, 'BorderFollowing', {}, ...
    'LastFW2Event', {});

numFrames = getLogFrameCount(trajectoryLog);
if numFrames == 0
    return;
end

rowIdx = 0;
for k = 1:numFrames
    step = collectOutputStepFromLogFrame(trajectoryLog.Frames(k), trajectoryLog);
    if ~isfield(step, 'Targets') || isempty(step.Targets)
        continue;
    end

    randomMode = string(step.RandomMode);
    scenarioSeed = step.ScenarioSeed;
    for i = 1:numel(step.Targets)
        rowIdx = rowIdx + 1;
        rows(rowIdx) = buildCsvRowFromTargetOutput( ...
            step.Time, randomMode, scenarioSeed, step.Targets(i));
    end
end
end
