function row = buildCsvRowFromTargetOutput(time, randomMode, scenarioSeed, targetOut)
% buildCsvRowFromTargetOutput - Одна строка трека CSV из legacy-выхода цели.
arguments
    time (1, 1) double
    randomMode (1, 1) string
    scenarioSeed (1, 1) double
    targetOut (1, 1) struct
end

pos = targetOut.Position(:);
vel = targetOut.Velocity(:);

row = struct( ...
    'Time', time, ...
    'RandomMode', randomMode, ...
    'ScenarioSeed', scenarioSeed, ...
    'ID', targetOut.ID, ...
    'Class', string(targetOut.Class), ...
    'Subtype', string(targetOut.Subtype), ...
    'TargetSeed', getTargetSeed(targetOut), ...
    'X', pos(1), ...
    'Y', pos(2), ...
    'Z', pos(3), ...
    'Vx', vel(1), ...
    'Vy', vel(2), ...
    'Vz', vel(3), ...
    'RCS', targetOut.RCS, ...
    'Visible', logical(targetOut.Visible), ...
    'State', string(targetOut.State), ...
    'Mission', string(targetOut.Mission), ...
    'CurrentTreeID', getOptionalNumericField(targetOut, 'CurrentTreeID'), ...
    'TargetTreeID', getOptionalNumericField(targetOut, 'TargetTreeID'), ...
    'TransitionCount', getOptionalNumericField(targetOut, 'TransitionCount', 0), ...
    'TransitionReason', string(getOptionalStringField(targetOut, 'TransitionReason')), ...
    'WaypointIndex', getOptionalNumericField(targetOut, 'WaypointIndex'), ...
    'DistanceToWaypoint', getOptionalNumericField(targetOut, 'DistanceToWaypoint'), ...
    'MissionComplete', getOptionalLogicalField(targetOut, 'MissionComplete', false), ...
    'NoProgressTime', getOptionalNumericField(targetOut, 'NoProgressTime'), ...
    'ForceDirectToWaypoint', getOptionalLogicalField(targetOut, 'ForceDirectToWaypoint', false), ...
    'TotalXYExcursion', getOptionalNumericField(targetOut, 'TotalXYExcursion'), ...
    'MaxAltitudeReached', getOptionalNumericField(targetOut, 'MaxAltitudeReached'), ...
    'MinAltitudeReached', getOptionalNumericField(targetOut, 'MinAltitudeReached'), ...
    'LastNavigationEvent', string(getOptionalStringField(targetOut, 'LastNavigationEvent')), ...
    'RoadID', getOptionalNumericField(targetOut, 'RoadID'), ...
    'CurrentEdgeID', getOptionalNumericField(targetOut, 'CurrentEdgeID'), ...
    'Waypoint', serializeVectorField(targetOut, 'Waypoint'), ...
    'SpeedLimit', getOptionalNumericField(targetOut, 'SpeedLimit'), ...
    'RoadDeviation', getOptionalNumericField(targetOut, 'RoadDeviation'), ...
    'RouteProgress', getOptionalNumericField(targetOut, 'RouteProgress'), ...
    'OnRoad', getOptionalLogicalField(targetOut, 'OnRoad', false), ...
    'IsOffRoad', getOptionalLogicalField(targetOut, 'IsOffRoad', false), ...
    'DriverProfile', string(getOptionalStringField(targetOut, 'DriverProfile')), ...
    'GroundAction', string(getOptionalStringField(targetOut, 'GroundAction')), ...
    'DesiredSpeed', getOptionalNumericField(targetOut, 'DesiredSpeed', 0), ...
    'DesiredAltitude', getOptionalNumericField(targetOut, 'DesiredAltitude'), ...
    'CurrentHeading', getOptionalNumericField(targetOut, 'CurrentHeading'), ...
    'TargetHeading', getOptionalNumericField(targetOut, 'TargetHeading'), ...
    'LoiterRadius', getOptionalNumericField(targetOut, 'LoiterRadius'), ...
    'DiveTargetAltitude', getOptionalNumericField(targetOut, 'DiveTargetAltitude'), ...
    'FlightLevel', getOptionalNumericField(targetOut, 'FlightLevel'), ...
    'TargetFlightLevel', getOptionalNumericField(targetOut, 'TargetFlightLevel'), ...
    'AltitudeError', getOptionalNumericField(targetOut, 'AltitudeError'), ...
    'DesiredClimbRate', getOptionalNumericField(targetOut, 'DesiredClimbRate'), ...
    'ClimbAngleDeg', getOptionalNumericField(targetOut, 'ClimbAngleDeg'), ...
    'TurnSeverity', getOptionalNumericField(targetOut, 'TurnSeverity'), ...
    'CornerCuttingActive', getOptionalLogicalField(targetOut, 'CornerCuttingActive', false), ...
    'FinalPhase', getOptionalLogicalField(targetOut, 'FinalPhase', false), ...
    'FinalStrategy', string(getOptionalStringField(targetOut, 'FinalStrategy')), ...
    'FinalPhaseStarted', getOptionalLogicalField(targetOut, 'FinalPhaseStarted', false), ...
    'FinalMissionCompleted', getOptionalLogicalField(targetOut, 'FinalMissionCompleted', false), ...
    'TimeInFinalPhase', getOptionalNumericField(targetOut, 'TimeInFinalPhase', 0), ...
    'DistanceToBoundary', getOptionalNumericField(targetOut, 'DistanceToBoundary'), ...
    'NearBoundary', getOptionalLogicalField(targetOut, 'NearBoundary', false), ...
    'OutsideBoundary', getOptionalLogicalField(targetOut, 'OutsideBoundary', false), ...
    'BoundaryRecoveryActive', getOptionalLogicalField(targetOut, 'BoundaryRecoveryActive', false), ...
    'LastBoundaryEvent', string(getOptionalStringField(targetOut, 'LastBoundaryEvent')), ...
    'HeadingJumpDeg', getOptionalNumericField(targetOut, 'HeadingJumpDeg', 0), ...
    'TargetPointJump', getOptionalNumericField(targetOut, 'TargetPointJump', 0), ...
    'AntiBounceActive', getOptionalLogicalField(targetOut, 'AntiBounceActive', false), ...
    'LastAntiBounceEvent', string(getOptionalStringField(targetOut, 'LastAntiBounceEvent')), ...
    'TimeOnCurrentLeg', getOptionalNumericField(targetOut, 'TimeOnCurrentLeg', 0), ...
    'Decision', string(getOptionalStringField(targetOut, 'Decision')), ...
    'BehaviorAction', string(getOptionalStringField(targetOut, 'BehaviorAction')), ...
    'BehaviorReason', string(getOptionalStringField(targetOut, 'BehaviorReason')), ...
    'BehaviorGoal', string(getOptionalStringField(targetOut, 'BehaviorGoal')), ...
    'BehaviorProfile', string(getOptionalStringField(targetOut, 'BehaviorProfile')), ...
    'RouteIndex', getOptionalNumericField(targetOut, 'RouteIndex'), ...
    'CurrentLegProgress', getOptionalNumericField(targetOut, 'CurrentLegProgress'), ...
    'BaseCruiseSpeed', getOptionalNumericField(targetOut, 'BaseCruiseSpeed'), ...
    'CurrentSpeed', getOptionalNumericField(targetOut, 'CurrentSpeed'), ...
    'TargetSpeed', getOptionalNumericField(targetOut, 'TargetSpeed'), ...
    'SpeedProfileEvent', string(getOptionalStringField(targetOut, 'SpeedProfileEvent')), ...
    'CurrentFlightLevel', getOptionalNumericField(targetOut, 'CurrentFlightLevel'), ...
    'HeadingErrorDeg', getOptionalNumericField(targetOut, 'HeadingErrorDeg'), ...
    'TurnRateCommandDeg', getOptionalNumericField(targetOut, 'TurnRateCommandDeg'), ...
    'AltitudeProfileEvent', string(getOptionalStringField(targetOut, 'AltitudeProfileEvent')), ...
    'InWarningZone', getOptionalLogicalField(targetOut, 'InWarningZone', false), ...
    'InCriticalZone', getOptionalLogicalField(targetOut, 'InCriticalZone', false), ...
    'BorderFollowing', getOptionalLogicalField(targetOut, 'BorderFollowing', false), ...
    'LastFW2Event', string(getOptionalStringField(targetOut, 'LastFW2Event')));
end

function value = serializeVectorField(target, fieldName)
if isfield(target, fieldName) && ~isempty(target.(fieldName))
    v = target.(fieldName);
    value = sprintf('%.3f %.3f %.3f', v(1), v(2), v(3));
else
    value = "";
end
end

function value = getOptionalNumericField(target, fieldName, defaultValue)
if nargin < 3
    defaultValue = NaN;
end
if isfield(target, fieldName) && ~isempty(target.(fieldName))
    value = target.(fieldName);
else
    value = defaultValue;
end
end

function value = getTargetSeed(target)
if isfield(target, 'TargetSeed') && ~isempty(target.TargetSeed)
    value = target.TargetSeed;
else
    value = getOptionalNumericField(target, 'RandomSeed');
end
end

function value = getOptionalStringField(target, fieldName)
if isfield(target, fieldName) && ~isempty(target.(fieldName))
    value = target.(fieldName);
else
    value = "";
end
end

function value = getOptionalLogicalField(target, fieldName, defaultValue)
if isfield(target, fieldName) && ~isempty(target.(fieldName))
    value = logical(target.(fieldName));
else
    value = logical(defaultValue);
end
end
