function exportOutputToCsv(output, config, outputFolder)
% exportOutputToCsv - Экспорт выходных данных симуляции в CSV-таблицу треков.
arguments
    output struct
    config (1, 1) struct
    outputFolder (1, :) char
end

rows = buildOutputTableRows(output);
T = struct2table(rows);
csvPath = fullfile(outputFolder, config.export.csvFileName);
writetable(T, csvPath);
end

function rows = buildOutputTableRows(output)
rows = struct( ...
    'Time', {}, 'RandomMode', {}, 'ScenarioSeed', {}, ...
    'ID', {}, 'Class', {}, 'Subtype', {}, 'TargetSeed', {}, ...
    'X', {}, 'Y', {}, 'Z', {}, ...
    'Vx', {}, 'Vy', {}, 'Vz', {}, ...
    'RCS', {}, 'Visible', {}, 'State', {}, 'Mission', {}, ...
    'CurrentTreeID', {}, 'TargetTreeID', {}, ...
    'TransitionCount', {}, 'TransitionReason', {}, ...
    'WaypointIndex', {}, 'DistanceToWaypoint', {}, 'MissionComplete', {}, ...
    'NoProgressTime', {}, 'ForceDirectToWaypoint', {}, ...
    'TotalXYExcursion', {}, 'MaxAltitudeReached', {}, 'MinAltitudeReached', {}, ...
    'LastNavigationEvent', {}, ...
    'RoadID', {}, 'CurrentEdgeID', {}, 'Waypoint', {}, 'SpeedLimit', {}, 'RoadDeviation', {}, ...
    'RouteProgress', {}, 'OnRoad', {}, 'IsOffRoad', {}, 'DriverProfile', {}, 'GroundAction', {}, ...
    'DesiredSpeed', {}, 'DesiredAltitude', {}, 'CurrentHeading', {}, ...
    'TargetHeading', {}, 'LoiterRadius', {}, 'DiveTargetAltitude', {}, ...
    'FlightLevel', {}, 'TargetFlightLevel', {}, 'AltitudeError', {}, ...
    'DesiredClimbRate', {}, 'ClimbAngleDeg', {}, 'TurnSeverity', {}, ...
    'CornerCuttingActive', {}, ...
    'FinalPhase', {}, 'FinalStrategy', {}, 'FinalPhaseStarted', {}, ...
    'FinalMissionCompleted', {}, 'TimeInFinalPhase', {}, ...
    'DistanceToBoundary', {}, 'NearBoundary', {}, 'OutsideBoundary', {}, ...
    'BoundaryRecoveryActive', {}, 'LastBoundaryEvent', {}, ...
    'HeadingJumpDeg', {}, 'TargetPointJump', {}, 'AntiBounceActive', {}, ...
    'LastAntiBounceEvent', {}, 'TimeOnCurrentLeg', {}, ...
    'Decision', {}, ...
    'BehaviorAction', {}, 'BehaviorReason', {}, 'BehaviorGoal', {}, ...
    'BehaviorProfile', {}, ...
    'RouteIndex', {}, 'CurrentLegProgress', {}, 'BaseCruiseSpeed', {}, ...
    'CurrentSpeed', {}, 'TargetSpeed', {}, 'SpeedProfileEvent', {}, ...
    'CurrentFlightLevel', {}, 'HeadingErrorDeg', {}, 'TurnRateCommandDeg', {}, ...
    'AltitudeProfileEvent', {}, ...
    'InWarningZone', {}, 'InCriticalZone', {}, 'BorderFollowing', {}, ...
    'LastFW2Event', {});

if isempty(output)
    return;
end

rowIdx = 0;
for k = 1:numel(output)
    step = output(k);
    if ~isfield(step, 'Targets') || isempty(step.Targets)
        continue;
    end

    randomMode = string(getStepStringField(step, 'RandomMode'));
    scenarioSeed = getStepNumericField(step, 'ScenarioSeed');
    for i = 1:numel(step.Targets)
        rowIdx = rowIdx + 1;
        rows(rowIdx) = buildCsvRowFromTargetOutput( ...
            step.Time, randomMode, scenarioSeed, step.Targets(i));
    end
end
end

function value = getStepNumericField(step, fieldName)
if isfield(step, fieldName) && ~isempty(step.(fieldName))
    value = step.(fieldName);
else
    value = NaN;
end
end

function value = getStepStringField(step, fieldName)
if isfield(step, fieldName) && ~isempty(step.(fieldName))
    value = step.(fieldName);
else
    value = "";
end
end
